### ISSUE TITLE
在mactex中编译无法找到引文的问题

### ISSUE THREAD

**Issue by Solipugids** [YimianDai/iNSFC#2]
我用的是mactex套件中的texshop排版的，顺序是xelatex>bibtex>xelatex，但是最终引文的地方发现只有问号，清理aux临时文件还是一样。
回头看在bibtex编译的时候发现报错如下：
INFO - This is Biber 2.7
INFO - Logfile is 'demo.blg'
ERROR - Cannot find control file 'demo.bcf'! - did you pass the "backend=biber" option to BibLaTeX?
INFO - ERRORS: 1
其他地方都没有做修改，请问这个是哪里有错误吗？谢谢！

**Comment by Solipugids** [comment]
在其他地方找到了答案，解决了我的问题。这应该是mactex套件下的特别问题，把答案链接贴在这里供其他人躲开这个坑。
[http://tex.stackexchange.com/questions/21486/error-message-when-using-biber](url)
其中一位回答者提到以下：

> 	
I have seen the same message when typesetting a tex file when using TeXShop.

Cannot find control file something.bcf did you pass the "backend=biber" option to BibLaTeX?
The message occurs when the tex file or other configuration files specify one BibTeX engine while TeXShop specifies another.

For example if the Engine settings in TeXShop prefs specify 'biber' rather than 'bibtex' while the tex file includes...

\usepackage[round]{natbib}
Conversely another tex file might use a class file to manage styles (.cls), specifying biber like so...

\RequirePackage[backend=biber]{biblatex}
In order to typeset from within TexShop, your prefs need to be changed to achieve agreement between the typesetting environment and the parameter in your file, e.g.: biber rather than bibtex, or bibtex rather than biber.

The problem does not occur when compiling from the command line using the desired BibTex engine.

**Comment by ivanshih** [comment]
我的使用三次 xelatex 没问题，两次xelatex也是问号（Ubuntu 14.04 + TeX Live 2016）:

$ xelatex demo.tex
$ bibtex demo
$ xelatex demo.tex
$ xelatex demo.tex

**Comment by YimianDai** [comment]
@ivanshih 应该是三次 xelatex 吧，我看刘海洋老师的《LaTeX 入门》上写的就是
```
$ xelatex demo.tex
$ bibtex demo.aux
$ xelatex demo.tex
$ xelatex demo.tex
```

**Comment by YimianDai** [comment]
@Solipugids Sorry，我没有 Mac，没法复现您的问题。请问按照 @ivanshih 说的三次 xelatex，您这个问题还存在吗？

**Comment by Solipugids** [comment]
我在回复里面有提到，stackexchange的回答者指出了问题所在：texshop在偏好设置里指定了bib文件的编译器是biber或者bibtex。在这里应该是修改成用bibtex编译，但是我之前的设置是biber，所以报错了。在命令行下编译的时候就不存在这个问题了。
另外，建议作者应该在sty中添加subsubsection的样式，我想不少写标书的人应该有这个需求。
