### ISSUE TITLE
subsection 数字编号后面的点号如何取消？

### ISSUE THREAD

**Issue by GuangmingChan** [YimianDai/iNSFC#23]
一般子标题最后的数字后面不需要有点号，比如，1.1. 相关工作，如何去掉1.1后面的点号？

**Comment by xh542428798** [comment]
我也想解决这个问题

**Comment by TomHeaven** [comment]
修改insfc.sty第79行为
```
\def\cvprsubsect#1{\cvprsubsection{\hskip -1em~#1 }\vspace{-0.2em}} % Tom: remove dot . here
```
其实就是把里面的点删掉。

**Comment by GuangmingChan** [comment]
> 修改insfc.sty第79行为
> 
> ```
> \def\cvprsubsect#1{\cvprsubsection{\hskip -1em~#1 }\vspace{-0.2em}} % Tom: remove dot . here
> ```
> 
> 其实就是把里面的点删掉。

非常感谢。已删掉 dot
