### ISSUE TITLE
2.1 研究内容和2.2 研究目标顺序问题

### ISSUE THREAD

**Issue by GuanghuiFU** [YimianDai/iNSFC#37]
首先感谢您提供的模板，节省了我大量排版时间！
有个小问题。

在第二章中，2．项目的研究内容、研究目标，以及拟解决的关键科学问题（此部分为重点阐述内容）；

应该先是2.1研究内容，再是2.2研究目标。贵模板中好像顺序错了？

**Comment by YimianDai** [comment]
您好！

「研究内容」和「研究目标」应该孰先孰后的问题，不同的人长期就有不同的选择。

我个人更喜欢先「研究目标」后「研究内容」，感觉这样安排更合理，先明确研究目标，后面围绕这个目标展开研究内容。
